config/routes.rb
Rails.application.routes.draw do
  root 'requests#index'

  resources :requests, only: [:index, :show, :create, :destroy] do
    get 'delete_all', to: 'requests#delete_all', on: :collection
  end
end

app/models/request.rb
class Request < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @requests = Request.order(created_at: :desc)
  end

  def show
    @request = Request.find(params[:id])
  end

  def create
    Request.create(
      method: request.method,
      headers: headers,
      body: body
    )
    render nothing: true, status: :ok
  end

  def destroy
    @request = Request.find(params[:id])
    @request.destroy
    redirect_to requests_path
  end

  def delete_all
    Request.destroy_all
    redirect_to requests_path
  end

  private

  def headers
    built_headers = {}
    relevant_keys.each do |key|
      built_headers[key] = request.headers[key]
    end
    built_headers
  end

  def relevant_keys
    request.headers.env.keys.select do |key|
      key.include?("CONTENT") || key.include?("HTTP")
    end
  end

  def body
    params.except(:controller, :action, :request)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebhookTestingApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/requests/index.html.slim
- if @requests.any?
  table
    tr
      th Method
      th Affiliate
      th Event
      th Sent At
    - @requests.each do |request|
      tr
        td = request.method
        td = link_to request.headers["HTTP_X_AFFILIATE_NAME"], request
        td = request.headers["HTTP_X_HRSC_EVENT"]
        td = time_ago_in_words(request.created_at) + " ago"

  = link_to 'Clear All', delete_all_requests_path

- else
  h2 No requests to display

app/views/requests/show.html.slim
h4 Request Method
p = @request.method
h4 Headers
p = simple_format JSON.pretty_generate(@request.headers)
h4 Body
p = simple_format JSON.pretty_generate(@request.body)
h4 Sent
p = time_ago_in_words(@request.created_at) + " ago"

= link_to 'Delete', @request, method: :delete